---
defaults:
  cameras: ['r1', 'r2', 'r3']
  interactive: auto
  check_pressure: true
  check_temperature: true
  max_temperature: '{{limits.temperature.max}}'
  max_pressure: '{{limits.pressure.max}}'
  min_purge_time: '{{limits.purge.min}}'
  max_purge_time: '{{limits.purge.max}}'
  min_fill_time: '{{limits.fill.min}}'
  max_fill_time: '{{limits.fill.max}}'
  use_thermistors: true
  quiet: false
  write_json: true
  write_log: true
  log_path: '/data/logs/ln2fills/{timestamp}'
  write_measurements: true
  measurements_path: '/data/logs/ln2fills/{timestamp}'
  measurements_extra_time: 0
  generate_qa: true
  qa_path: '/data/logs/ln2fills/{timestamp}'
  slack: true
  slack_route: http://lvm-hub.lco.cl/restapi/slack/alert/
  email: false
  email_recipients: lvm-critical@sdss.org

valves:
  r1:
    actor: lvmnps.sp1
    outlet: r1
  b1:
    actor: lvmnps.sp1
    outlet: b1
  z1:
    actor: lvmnps.sp1
    outlet: z1
  r2:
    actor: lvmnps.sp2
    outlet: r2
  b2:
    actor: lvmnps.sp2
    outlet: b2
  z2:
    actor: lvmnps.sp2
    outlet: z2
  r3:
    actor: lvmnps.sp3
    outlet: r3
  b3:
    actor: lvmnps.sp3
    outlet: b3
  z3:
    actor: lvmnps.calib
    outlet: outlet_7
  purge:
    actor: lvmnps.calib
    outlet: outlet8
    thermistor: supply

limits:
  pressure:
    min: null
    max: 0.001
  temperature:
    min: null
    max: -140
  purge:
    min: 1500
    max: 1920
  fill:
    min: 120
    max: 360

api:
  url: http://lvm-hub.lco.cl:8080/restapi/

rabbitmq:
  host: lvm-hub.lco.cl
  port: 5672

thermistors:
  host: 10.8.38.180
  port: 1025
  mapping:
    channel7: supply
    channel8: r1
    channel9: b1
    channel6: z1
    channel10: r3
    channel11: b3
    channel12: z3
    channel13: r2
    channel14: b2
    channel15: z2

ion:
  z2:
    host: 10.8.38.156
    port: 502
    signal_address: 0
    onoff_address: 2020
  b2:
    host: 10.8.38.155
    port: 502
    signal_address: 2
    onoff_address: 2021
  r2:
    host: 10.8.38.155
    port: 502
    signal_address: 4
    onoff_address: 2022

notifications: false
