---
defaults:
  cameras: ['r1', 'r2', 'r3']
  interactive: auto
  no_prompt: null
  check_pressure: true
  check_temperature: true
  max_temperature: -140
  max_pressure: 0.001
  min_purge_time: 1500
  max_purge_time: 2000
  min_fill_time: 120
  max_fill_time: 360
  use_thermistors: true
  log_path: '/data/logs/lvmcryo/{timestamp}.log'
  data_path: '/data/logs/lvmcryo/{timestamp}.parquet'

notifications:
  slack_route: http://localhost:8888/slack/message
  slack_channels:
    info: lvm-notifications
    error: lvm-alerts
  slack_mentions:
    error: '@here'
  email_recipients:
    - lvm-critical@sdss.org
  email_server: smtp-02.lco.cl
  email_from: 'LVM LN2 system <lvm-ln2@lco.cl>'
  email_reply_to: 'lvm-inst@sdss.org'

valves:
  r1:
    actor: lvmnps.sp1
    outlet: r1
  b1:
    actor: lvmnps.sp1
    outlet: b1
  z1:
    actor: lvmnps.sp1
    outlet: z1
  r2:
    actor: lvmnps.sp2
    outlet: r2
  b2:
    actor: lvmnps.sp2
    outlet: b2
  z2:
    actor: lvmnps.sp2
    outlet: z2
  r3:
    actor: lvmnps.sp3
    outlet: r3
  b3:
    actor: lvmnps.sp3
    outlet: b3
  z3:
    actor: lvmnps.calib
    outlet: outlet_7
  purge:
    actor: lvmnps.calib
    outlet: outlet8
    thermistor: supply
